#!/usr/bin/env python# coding=utf-8
"""
Locust quickstart!
Copyright 2015.05.08 Rongzhong.Xu xurongzhong#126.com
http://automationtesting.sinaapp.com
"""
from locust import HttpLocust, TaskSet, task
import json

class UserBehavior(TaskSet):

    """
    Locust test class
    """

    def on_start(self):
        """ called when a Locust start before any task is scheduled """
        print "on_start"

    @task(1)
    def index(self):

        payload = {"cards":[{"card":"7310191000000102421"},{"card":"7310191000000102413"}]}
        headers = {'content-type': 'application/json'}
        # r = l.client.post("/post/endpoint", data=json.dumps(payload), headers=headers, catch_response=True)
        response = self.client.post("/ServiceGroupPortal/yumCard/getCardInfo",data=json.dumps(payload), headers=headers)
        print "Response status code:", response.status_code
        print "Response content:", response.content

class WebsiteUser(HttpLocust):
    print "WebsiteUser"
    task_set = UserBehavior
    min_wait = 0
    max_wait = 0
